print("type()---------------------")
sentence = '   My favorite fruit is banana .         '
print(type(sentence))
print("help()---------------------")
print(help(sentence))
print(help(sentence.capitalize))
print("upper()---------------------")
print(sentence.upper())
print("lower()---------------------")
print(sentence.lower())
print("find()---------------------")
print(sentence.find("a"))
print("find()---------------------")
print(sentence.strip())
print("startswith()---------------------")
print(sentence.startswith("My"))
print(sentence.startswith(" "))
print(sentence.strip().startswith("My"))

print(sentence.upper().strip())
print(sentence.lower().strip())
print(sentence.upper().strip().startswith("My"))
print(sentence.lower().strip().startswith("My"))